/*
 * generated by Xtext 2.21.0
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CryslUiModule extends AbstractCryslUiModule {

	public CryslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
