/*
 * generated by Xtext 2.21.0
 */
package org;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CryslStandaloneSetup extends CryslStandaloneSetupGenerated {

	public static void doSetup() {
		new CryslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
